# Population Dataset analysis

Data from the datagouv.fr french goverment website, 
Ref - "Municipal populations from 1968 to 2023"

In [1]:
import pandas as pd
import numpy as np

Global duckdb

In [14]:
import duckdb
con = duckdb.connect()

# load the table
def load_table(df, name):
    con.register(name, df)

# run the query
def run(query):
    return con.execute(query).df()

In [2]:
# File paths
population_csv = '../Data/population_data.csv'
population_meta_csv = '../Data/population_metadata.csv'

In [3]:
pop_raw = pd.read_csv(population_csv,sep=';')
pop_meta_raw = pd.read_csv(population_meta_csv,sep=';')

/tmp/ipykernel_31313/257530682.py:1: DtypeWarning: Columns (0: GEO) have mixed types. Specify dtype option on import or set low_memory=False.
  pop_raw = pd.read_csv(population_csv,sep=';')

In [4]:
pop_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 813234 entries, 0 to 813233
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   FREQ            813234 non-null  str
 1   GEO             813234 non-null  object
 2   GEO_OBJECT      813234 non-null  str
 3   POPREF_MEASURE  813234 non-null  str
 4   TIME_PERIOD     813234 non-null  int64
 5   OBS_VALUE       813234 non-null  int64
dtypes: int64(2), object(1), str(3)
memory usage: 43.4+ MB

In [22]:
pop_raw.isnull().sum()

FREQ              0
GEO               0
GEO_OBJECT        0
POPREF_MEASURE    0
TIME_PERIOD       0
OBS_VALUE         0
dtype: int64

In [20]:
pop_raw.describe()

         TIME_PERIOD     OBS_VALUE
count  813234.000000  8.132340e+05
mean     2007.608696  1.084408e+04
std        14.761119  4.873658e+05
min      1968.000000  0.000000e+00
25%      2006.000000  1.940000e+02
50%      2012.000000  4.390000e+02
75%      2018.000000  1.134000e+03
max      2023.000000  6.809428e+07

- the time periode covers min=1968 and max=2023
- the obs_value from 0 to 68094280

In [11]:
pop_raw.head(5)

  FREQ    GEO GEO_OBJECT POPREF_MEASURE  TIME_PERIOD  OBS_VALUE
0    A  15113        COM           PMUN         2010        197
1    A  14491        COM           PMUN         2007        154
2    A  14761        COM           PMUN         2011        746
3    A  14700        COM           PMUN         2018        663
4    A  15038        COM           PMUN         2013       1040

In [12]:
pop_meta_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 35384 entries, 0 to 35383
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COD_VAR  35384 non-null  str
 1   LIB_VAR  35384 non-null  str
 2   COD_MOD  35384 non-null  str
 3   LIB_MOD  35384 non-null  str
dtypes: str(4)
memory usage: 2.1 MB

In [20]:
pop_meta_raw.isnull().sum()

COD_VAR    0
LIB_VAR    0
COD_MOD    0
LIB_MOD    0
dtype: int64

In [7]:
print(pop_raw.sample(5))

       FREQ    GEO GEO_OBJECT POPREF_MEASURE  TIME_PERIOD  OBS_VALUE
463882    A  80013        COM           PMUN         2012       2363
560696    A  17057        COM           PSDC         1982        377
655373    A  66040        COM           PSDC         1975         31
537726    A  10258        COM           PSDC         1968        320
209559    A  45164        COM           PMUN         2008        651

In [18]:
pop_raw.POPREF_MEASURE.unique()

<ArrowStringArray>
['PMUN', 'PSDC']
Length: 2, dtype: str

In [6]:
print(pop_meta_raw.sample(5))

      COD_VAR     LIB_VAR COD_MOD                    LIB_MOD
15337     GEO  Géographie   40288                   Sarbazan
24803     GEO  Géographie   63004          Les Ancizes-Comps
31829     GEO  Géographie   79139            Les Groseillers
1174      GEO  Géographie   02791                     Veslud
18523     GEO  Géographie   50448  Saint-Aubin-de-Terregatte

In [9]:
com_data = pd.read_csv('../Data/v_commune_2026.csv')

In [12]:
com_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 37496 entries, 0 to 37495
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TYPECOM    37496 non-null  str
 1   COM        37496 non-null  str
 2   REG        34920 non-null  float64
 3   DEP        34920 non-null  str
 4   CTCD       34920 non-null  str
 5   ARR        34903 non-null  str
 6   TNCC       37496 non-null  int64
 7   NCC        37496 non-null  str
 8   NCCENR     37496 non-null  str
 9   LIBELLE    37496 non-null  str
 10  CAN        34864 non-null  str
 11  COMPARENT  2621 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 5.4 MB

In [17]:
com_data.sample(5)

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
25937,COM,62545,32.0,62,62D,624,0,MANINGHEM,Maninghem,Maninghem,6233,NaN
30341,COM,71495,27.0,71,71D,715,0,SALORNAY SUR GUYE,Salornay-sur-Guye,Salornay-sur-Guye,7111,NaN
15657,COM,39310,27.0,39,39D,392,0,MANTRY,Mantry,Mantry,3903,NaN
16197,COM,40293,75.0,40,40D,401,0,SAUBUSSE,Saubusse,Saubusse,4009,NaN
20911,COM,53135,52.0,53,53D,531,0,LIVRE LA TOUCHE,Livré-la-Touche,Livré-la-Touche,5304,NaN

In [16]:
com_data.TYPECOM.unique()

<ArrowStringArray>
['COM', 'COMD', 'COMA', 'ARM']
Length: 4, dtype: str

In [15]:
load_table(com_data, 'commap')