# Energy Production eda

In [1]:
import pandas as pd
import numpy as np
import duckdb

In [2]:
con = duckdb.connect()

# load the table
def load_table(df, name):
    con.register(name, df)
    
# run the query
def run(query):
    return con.execute(query).df()

In [62]:
prod_filiere_path = '../Data/prod-region-annuelle-filiere.csv'
prod_enr_path = '../Data/prod-region-annuelle-enr.csv'

In [63]:
epr = pd.read_csv(prod_enr_path, sep=';')
epf = pd.read_csv(prod_filiere_path, sep=';')

In [64]:
epr.sample(10)

,Annee,Nom INSEE région,Code INSEE région,Production hydraulique renouvelable (GWh),Production bioénergies renouvelable (GWh),Production éolienne renouvelable (GWh),Production solaire renouvelable (GWh),Production électrique renouvelable (GWh),Production gaz renouvelable (GWh),Production totale renouvelable (GWh),Géo-shape région,Géo-point région
91,2010,Bretagne,53,540.100,65.20,906.00,29.20,1540.500,0.000000,1540.500000,"{""coordinates"": [[[[-3.194814966, 47.365416018...","48.177551218, -2.841488793"
8,2013,Occitanie,76,11961.500,508.10,2197.10,989.80,15656.500,0.000000,15656.500000,"{""coordinates"": [[[[-0.07519535, 43.307155125]...","43.702500286, 2.143923389"
73,2021,Pays de la Loire,52,24.032,402.21,2246.50,770.04,3442.782,304.000000,3746.782000,"{""coordinates"": [[[[-2.337432985, 46.719095681...","47.478103923, -0.816788181"
92,2013,Centre-Val de Loire,24,171.400,233.60,1513.20,166.40,2084.600,0.000000,2084.600000,"{""coordinates"": [[[2.936623684, 48.163455797],...","47.48477569, 1.684391194"
12,2008,Île-de-France,11,59.000,629.90,NaN,0.70,689.600,0.000000,689.600000,"{""coordinates"": [[[3.485019233, 48.851845323],...","48.7093154, 2.503402421"
118,2018,Pays de la Loire,52,19.215,317.98,1631.66,546.36,2515.215,68.200000,2583.415000,"{""coordinates"": [[[[-2.337432985, 46.719095681...","47.478103923, -0.816788181"
209,2014,Pays de la Loire,52,23.584,281.86,1072.29,368.37,1746.104,NaN,1746.104000,"{""coordinates"": [[[[-2.337432985, 46.719095681...","47.478103923, -0.816788181"
109,2015,Bretagne,53,531.859,229.91,1651.00,187.34,2600.109,1.400000,2601.509000,"{""coordinates"": [[[[-3.194814966, 47.365416018...","48.177551218, -2.841488793"
85,2025,Corse,94,435.407,2.98,24.60,301.92,764.907,NaN,764.907000,"{""coordinates"": [[[8.6794044, 42.467320898], [...","42.151503519, 9.10615502"
35,2024,Nouvelle-Aquitaine,75,5657.746,1429.98,3327.74,5797.67,16213.136,1098.233419,17311.369419,"{""coordinates"": [[[[-1.412478526, 46.184385107...","45.206826366, 0.207571781"

In [65]:
epr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 12 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Annee                                      234 non-null    int64
 1   Nom INSEE région                           234 non-null    object
 2   Code INSEE région                          234 non-null    int64
 3   Production hydraulique renouvelable (GWh)  234 non-null    float64
 4   Production bioénergies renouvelable (GWh)  233 non-null    float64
 5   Production éolienne renouvelable (GWh)     231 non-null    float64
 6   Production solaire renouvelable (GWh)      234 non-null    float64
 7   Production électrique renouvelable (GWh)   234 non-null    float64
 8   Production gaz renouvelable (GWh)          205 non-null    float64
 9   Production totale renouvelable (GWh)       234 non-null    float64
 10  Géo-shape région                           234 non-null    object
 11  Géo-point région                           234 non-null    object
dtypes: float64(7), int64(2), object(3)
memory usage: 22.1+ KB

In [66]:
epr.describe()

,Annee,Code INSEE région,Production hydraulique renouvelable (GWh),Production bioénergies renouvelable (GWh),Production éolienne renouvelable (GWh),Production solaire renouvelable (GWh),Production électrique renouvelable (GWh),Production gaz renouvelable (GWh),Production totale renouvelable (GWh)
count,234.000000,234.000000,234.000000,233.000000,231.000000,234.000000,234.000000,205.000000,234.000000
mean,2016.500000,53.307692,4461.215030,477.932403,2051.199437,816.555513,7778.562509,180.016133,7936.268950
std,5.199249,27.350047,7018.987965,343.873413,2551.264741,1222.679547,7983.263948,386.215626,8068.827892
min,2008.000000,11.000000,3.700000,1.910000,9.200000,0.200000,341.200000,0.000000,341.200000
25%,2012.000000,28.000000,96.809250,235.900000,304.335000,108.217500,1514.278500,0.000000,1594.616750
50%,2016.500000,52.000000,543.430000,400.960000,1310.830000,290.045000,4070.052000,6.900000,4312.910500
75%,2021.000000,76.000000,7864.445000,700.040000,2656.735000,984.145000,12620.200250,156.000000,12895.504750
max,2025.000000,94.000000,30409.800000,1456.870000,14533.120000,7484.730000,35222.209000,2618.482824,35875.281117

In [67]:
epr.columns

Index(['Annee', 'Nom INSEE région', 'Code INSEE région',
       'Production hydraulique renouvelable (GWh)',
       'Production bioénergies renouvelable (GWh)',
       'Production éolienne renouvelable (GWh)',
       'Production solaire renouvelable (GWh)',
       'Production électrique renouvelable (GWh)',
       'Production gaz renouvelable (GWh)',
       'Production totale renouvelable (GWh)', 'Géo-shape région',
       'Géo-point région'],
      dtype='object')

In [68]:
regions_enr = epr['Nom INSEE région'].unique()
print(len(regions_enr))
regions_enr

13

array(['Centre-Val de Loire', 'Hauts-de-France', 'Grand Est',
       'Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Corse',
       'Île-de-France', 'Occitanie', 'Nouvelle-Aquitaine', 'Bretagne',
       'Pays de la Loire', "Provence-Alpes-Côte d'Azur", 'Normandie'],
      dtype=object)

In [69]:
print(epr['Annee'].min())
print(epr['Annee'].max())

2008
2025

In [70]:
epr.isnull().sum()

Annee                                         0
Nom INSEE région                              0
Code INSEE région                             0
Production hydraulique renouvelable (GWh)     0
Production bioénergies renouvelable (GWh)     1
Production éolienne renouvelable (GWh)        3
Production solaire renouvelable (GWh)         0
Production électrique renouvelable (GWh)      0
Production gaz renouvelable (GWh)            29
Production totale renouvelable (GWh)          0
Géo-shape région                              0
Géo-point région                              0
dtype: int64

## Epf

In [71]:
epf.isnull().sum()

Année                             0
Code INSEE région                 0
Région                            0
Production nucléaire (GWh)      108
Production thermique (GWh)        0
Production hydraulique (GWh)      0
Production éolienne (GWh)         3
Production solaire (GWh)          0
Production bioénergies (GWh)      1
Géo-shape région                  0
Géo-point région                  0
dtype: int64

In [72]:
epf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Année                         234 non-null    int64
 1   Code INSEE région             234 non-null    int64
 2   Région                        234 non-null    object
 3   Production nucléaire (GWh)    126 non-null    float64
 4   Production thermique (GWh)    234 non-null    float64
 5   Production hydraulique (GWh)  234 non-null    float64
 6   Production éolienne (GWh)     231 non-null    float64
 7   Production solaire (GWh)      234 non-null    float64
 8   Production bioénergies (GWh)  233 non-null    float64
 9   Géo-shape région              234 non-null    object
 10  Géo-point région              234 non-null    object
dtypes: float64(6), int64(2), object(3)
memory usage: 20.2+ KB

In [73]:
epf.describe()

,Année,Code INSEE région,Production nucléaire (GWh),Production thermique (GWh),Production hydraulique (GWh),Production éolienne (GWh),Production solaire (GWh),Production bioénergies (GWh)
count,234.000000,234.000000,126.000000,234.000000,234.000000,231.000000,234.000000,233.000000
mean,2016.500000,53.307692,54320.693651,3170.509829,4830.717094,2051.195238,816.546154,623.132189
std,5.199249,27.350047,23928.507324,3227.293592,7710.638117,2551.242709,1222.673961,405.182052
min,2008.000000,11.000000,4523.000000,149.000000,3.700000,9.000000,0.200000,2.000000
25%,2012.000000,28.000000,35460.500000,762.750000,96.750000,304.500000,108.100000,342.000000
50%,2016.500000,52.000000,58841.000000,1705.000000,585.000000,1311.000000,290.000000,512.300000
75%,2021.000000,76.000000,76227.000000,5146.025000,8422.000000,2656.500000,984.100000,963.000000
max,2025.000000,94.000000,90853.000000,13147.000000,32983.500000,14533.000000,7485.000000,1610.000000

In [75]:
print(epf['Année'].min())
print(epf['Année'].max())

2008
2025

In [76]:
epf['Région'].unique()

array(['Île-de-France', 'Centre-Val de Loire', 'Bourgogne-Franche-Comté',
       'Normandie', 'Pays de la Loire', 'Nouvelle-Aquitaine',
       "Provence-Alpes-Côte d'Azur", 'Hauts-de-France', 'Grand Est',
       'Bretagne', 'Occitanie', 'Auvergne-Rhône-Alpes', 'Corse'],
      dtype=object)

In [78]:
epf.isnull().sum()

Année                             0
Code INSEE région                 0
Région                            0
Production nucléaire (GWh)      108
Production thermique (GWh)        0
Production hydraulique (GWh)      0
Production éolienne (GWh)         3
Production solaire (GWh)          0
Production bioénergies (GWh)      1
Géo-shape région                  0
Géo-point région                  0
dtype: int64