# Weather data EDA

In [1]:
import pandas as pd
import numpy as np
import duckdb

In [2]:
con = duckdb.connect()

# load the table
def load_table(df, name):
    con.register(name, df)
    
# run the query
def run(query):
    return con.execute(query).df()

In [3]:
weather_data_path = '../Data/temperature-quotidienne-regionale.csv'

In [4]:
weather_data = pd.read_csv(weather_data_path,sep=';')

In [5]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48607 entries, 0 to 48606
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 48607 non-null  object
 1   Date               48607 non-null  object
 2   Code INSEE région  48607 non-null  int64
 3   Région             48607 non-null  object
 4   TMin (°C)          48607 non-null  float64
 5   TMax (°C)          48607 non-null  float64
 6   TMoy (°C)          48607 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.6+ MB

In [6]:
weather_data.sample(3)

,ID,Date,Code INSEE région,Région,TMin (°C),TMax (°C),TMoy (°C)
4267,2019-05-28T00:00:00-53,2019-05-28,53,Bretagne,9.68,17.05,13.36
43642,2022-01-17T00:00:00-93,2022-01-17,93,Provence-Alpes-Côte d'Azur,0.43,12.05,6.24
8820,2022-03-04T00:00:00-53,2022-03-04,53,Bretagne,4.88,11.20,8.04

In [ ]:
print(f'max date: {weather_data.Date.max()}')
print(f'min date:{weather_data.Date.min()}')

max date: 2026-04-29
fmin date:2016-01-01

In [16]:
weather_data['Région'].unique()

array(['Île-de-France', 'Corse', 'Auvergne-Rhône-Alpes',
       "Provence-Alpes-Côte d'Azur", 'Pays de la Loire',
       'Bourgogne-Franche-Comté', 'Grand Est', 'Bretagne', 'Occitanie',
       'Centre-Val de Loire', 'Hauts-de-France', 'Nouvelle-Aquitaine',
       'Normandie'], dtype=object)

In [9]:
insee_code = weather_data['Code INSEE région'].unique()
print(f"{insee_code} there are {len(insee_code)} regions")

[11 94 84 93 52 27 44 53 76 24 32 75 28] there are 13 regions

In [10]:
weather_data.isnull().sum()

ID                   0
Date                 0
Code INSEE région    0
Région               0
TMin (°C)            0
TMax (°C)            0
TMoy (°C)            0
dtype: int64

In [11]:
weather_data.describe()

       Code INSEE région     TMin (°C)     TMax (°C)     TMoy (°C)
count       48607.000000  48607.000000  48607.000000  48607.000000
mean           53.307692      8.569881     17.902051     13.235961
std            27.291825      5.848722      7.577123      6.474719
min            11.000000    -11.980000     -3.750000     -6.480000
25%            28.000000      4.340000     12.230000      8.510000
50%            52.000000      8.500000     17.440000     12.780000
75%            76.000000     13.000000     23.440000     18.120000
max            94.000000     25.400000     41.680000     32.700000

TODO:
- need to eda weather and production data quickly then move to the schema building stage.